// <auto-generated />
using System;
using CostAllocationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CostAllocationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CostAllocationService.Models.CostAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AllocationRule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EntitlementId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("cost_allocation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllocatedCost = 20000m,
                            AllocationRule = "fixed_split",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            EntitlementId = 1,
                            Percentage = 20m
                        },
                        new
                        {
                            Id = 2,
                            AllocatedCost = 10000m,
                            AllocationRule = "fixed_split",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            EntitlementId = 1,
                            Percentage = 10m
                        },
                        new
                        {
                            Id = 3,
                            AllocatedCost = 30000m,
                            AllocationRule = "usage_based",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            EntitlementId = 2,
                            Percentage = 30m
                        },
                        new
                        {
                            Id = 4,
                            AllocatedCost = 15000m,
                            AllocationRule = "usage_based",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            EntitlementId = 2,
                            Percentage = 15m
                        },
                        new
                        {
                            Id = 5,
                            AllocatedCost = 25000m,
                            AllocationRule = "fixed_split",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            EntitlementId = 3,
                            Percentage = 25m
                        },
                        new
                        {
                            Id = 6,
                            AllocatedCost = 5000m,
                            AllocationRule = "fixed_split",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 6,
                            EntitlementId = 3,
                            Percentage = 5m
                        },
                        new
                        {
                            Id = 7,
                            AllocatedCost = 40000m,
                            AllocationRule = "usage_based",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 7,
                            EntitlementId = 4,
                            Percentage = 40m
                        },
                        new
                        {
                            Id = 8,
                            AllocatedCost = 10000m,
                            AllocationRule = "usage_based",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 8,
                            EntitlementId = 4,
                            Percentage = 10m
                        },
                        new
                        {
                            Id = 9,
                            AllocatedCost = 15000m,
                            AllocationRule = "fixed_split",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 9,
                            EntitlementId = 5,
                            Percentage = 15m
                        },
                        new
                        {
                            Id = 10,
                            AllocatedCost = 5000m,
                            AllocationRule = "fixed_split",
                            CalculatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 10,
                            EntitlementId = 5,
                            Percentage = 5m
                        });
                });

            modelBuilder.Entity("CostAllocationService.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerId = 101,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            ManagerId = 102,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            ManagerId = 103,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 4,
                            ManagerId = 104,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            ManagerId = 105,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            ManagerId = 106,
                            Name = "IT Support"
                        },
                        new
                        {
                            Id = 7,
                            ManagerId = 107,
                            Name = "Security"
                        },
                        new
                        {
                            Id = 8,
                            ManagerId = 108,
                            Name = "Infrastructure"
                        },
                        new
                        {
                            Id = 9,
                            ManagerId = 109,
                            Name = "Product"
                        },
                        new
                        {
                            Id = 10,
                            ManagerId = 110,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("CostAllocationService.Models.CostAllocation", b =>
                {
                    b.HasOne("CostAllocationService.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
