// <auto-generated />
using System;
using AssignmentsInventoryMicroService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssignmentsInventoryMicroService.Migrations
{
    [DbContext(typeof(AssignmentsInventoryDbContext))]
    [Migration("20251126100454_firstTest")]
    partial class firstTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssignmentsInventoryMicroService.Models.ComplianceAuditSnapshot", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssignedCount")
                        .HasColumnType("int");

                    b.Property<int>("EntitlementsPurchased")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.ToTable("audits", (string)null);

                    b.HasData(
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000001"),
                            AssignedCount = 50,
                            EntitlementsPurchased = 55,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SnapshotTime = new DateTime(2024, 10, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Compliant",
                            UsedCount = 45
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000002"),
                            AssignedCount = 60,
                            EntitlementsPurchased = 55,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SnapshotTime = new DateTime(2024, 11, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "OverLicensed",
                            UsedCount = 40
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000003"),
                            AssignedCount = 20,
                            EntitlementsPurchased = 20,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            SnapshotTime = new DateTime(2024, 12, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Compliant",
                            UsedCount = 18
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000004"),
                            AssignedCount = 25,
                            EntitlementsPurchased = 20,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            SnapshotTime = new DateTime(2024, 12, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "OverLicensed",
                            UsedCount = 5
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000005"),
                            AssignedCount = 5,
                            EntitlementsPurchased = 5,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SnapshotTime = new DateTime(2024, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Compliant",
                            UsedCount = 5
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000006"),
                            AssignedCount = 7,
                            EntitlementsPurchased = 5,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SnapshotTime = new DateTime(2024, 12, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "UnderLicensed",
                            UsedCount = 7
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000007"),
                            AssignedCount = 30,
                            EntitlementsPurchased = 30,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SnapshotTime = new DateTime(2024, 12, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Compliant",
                            UsedCount = 29
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000008"),
                            AssignedCount = 35,
                            EntitlementsPurchased = 35,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            SnapshotTime = new DateTime(2024, 12, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Compliant",
                            UsedCount = 32
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000009"),
                            AssignedCount = 15,
                            EntitlementsPurchased = 20,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            SnapshotTime = new DateTime(2024, 11, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "OverLicensed",
                            UsedCount = 3
                        },
                        new
                        {
                            AuditId = new Guid("80000000-0000-0000-0000-000000000010"),
                            AssignedCount = 10,
                            EntitlementsPurchased = 10,
                            ProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            SnapshotTime = new DateTime(2024, 11, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Compliant",
                            UsedCount = 9
                        });
                });

            modelBuilder.Entity("AssignmentsInventoryMicroService.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId");

                    b.ToTable("devices", (string)null);

                    b.HasData(
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000001"),
                            DeviceType = "Desktop",
                            Hostname = "DESKTOP-IT-01",
                            LastSeen = new DateTime(2025, 1, 1, 9, 10, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Status = "Active"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000002"),
                            DeviceType = "Laptop",
                            Hostname = "LAPTOP-FIN-01",
                            LastSeen = new DateTime(2025, 1, 1, 9, 20, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Status = "Active"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000002"),
                            DeviceType = "Laptop",
                            Hostname = "LAPTOP-FIN-02",
                            LastSeen = new DateTime(2025, 1, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000007"),
                            Status = "Active"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000003"),
                            DeviceType = "Laptop",
                            Hostname = "LAPTOP-HR-01",
                            LastSeen = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Status = "Active"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000004"),
                            DeviceType = "Server",
                            Hostname = "SERVER-APP-01",
                            LastSeen = new DateTime(2025, 1, 1, 7, 0, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Status = "Active"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000006"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000004"),
                            DeviceType = "Server",
                            Hostname = "SERVER-DB-01",
                            LastSeen = new DateTime(2024, 12, 31, 21, 0, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Status = "Active"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000007"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000004"),
                            DeviceType = "Laptop",
                            Hostname = "LAPTOP-ENG-01",
                            LastSeen = new DateTime(2025, 1, 1, 9, 5, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Status = "Active"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000004"),
                            DeviceType = "Laptop",
                            Hostname = "LAPTOP-ENG-02",
                            LastSeen = new DateTime(2025, 1, 1, 8, 55, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Status = "Inactive"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000009"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000001"),
                            DeviceType = "VDI",
                            Hostname = "VDI-IT-01",
                            LastSeen = new DateTime(2024, 12, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000008"),
                            Status = "Active"
                        },
                        new
                        {
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000010"),
                            DepartmentId = new Guid("40000000-0000-0000-0000-000000000005"),
                            DeviceType = "Laptop",
                            Hostname = "LAPTOP-SALES-01",
                            LastSeen = new DateTime(2025, 1, 1, 9, 45, 0, 0, DateTimeKind.Utc),
                            OwnerUserId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("AssignmentsInventoryMicroService.Models.Installation", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Discovered")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EntitlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstallationId");

                    b.HasIndex("DeviceId");

                    b.ToTable("installations", (string)null);

                    b.HasData(
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000001"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000001"),
                            InstallDate = new DateTime(2024, 10, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2025, 1, 1, 9, 10, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Version = "Microsoft 365 Apps"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000002"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000002"),
                            InstallDate = new DateTime(2024, 10, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2025, 1, 1, 9, 20, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Version = "Microsoft 365 Apps"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000003"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000008"),
                            InstallDate = new DateTime(2024, 11, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2025, 1, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Version = "Power BI Desktop"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000004"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000001"),
                            InstallDate = new DateTime(2024, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Version = "Microsoft 365 Apps"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000005"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000009"),
                            InstallDate = new DateTime(2024, 7, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2025, 1, 1, 7, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Version = "Jira Server 9.0"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000006"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000005"),
                            InstallDate = new DateTime(2024, 6, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2024, 12, 31, 21, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Version = "SQL Server 2019"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000007"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000004"),
                            InstallDate = new DateTime(2024, 12, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2025, 1, 1, 9, 5, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Version = "VS 2022 Enterprise"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000008"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000003"),
                            InstallDate = new DateTime(2024, 12, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2025, 1, 1, 8, 55, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Version = "Photoshop 2024"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000009"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000007"),
                            InstallDate = new DateTime(2024, 11, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2024, 12, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Version = "Slack Desktop"
                        },
                        new
                        {
                            InstallationId = new Guid("50000000-0000-0000-0000-000000000010"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Discovered = true,
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000006"),
                            InstallDate = new DateTime(2024, 12, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2025, 1, 1, 9, 45, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Version = "Zoom Client 5.x"
                        });
                });

            modelBuilder.Entity("AssignmentsInventoryMicroService.Models.UsageEvent", b =>
                {
                    b.Property<Guid>("UsageEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsageEventId");

                    b.HasIndex("DeviceId");

                    b.ToTable("usage_tracking", (string)null);

                    b.HasData(
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000001"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DurationSeconds = 5400,
                            EventType = "session_start",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SessionId = new Guid("71000000-0000-0000-0000-000000000001"),
                            Timestamp = new DateTime(2025, 1, 1, 7, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000002"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DurationSeconds = 3600,
                            EventType = "session_start",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SessionId = new Guid("71000000-0000-0000-0000-000000000002"),
                            Timestamp = new DateTime(2025, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000003"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DurationSeconds = 900,
                            EventType = "report_refresh",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Timestamp = new DateTime(2025, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000004"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DurationSeconds = 2700,
                            EventType = "session_start",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SessionId = new Guid("71000000-0000-0000-0000-000000000004"),
                            Timestamp = new DateTime(2025, 1, 1, 4, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000005"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000006"),
                            DurationSeconds = 7200,
                            EventType = "db_maintenance",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Timestamp = new DateTime(2024, 12, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000006"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000007"),
                            DurationSeconds = 1200,
                            EventType = "build_solution",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Timestamp = new DateTime(2025, 1, 1, 7, 30, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000007"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000010"),
                            DurationSeconds = 3600,
                            EventType = "meeting_join",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SessionId = new Guid("71000000-0000-0000-0000-000000000007"),
                            Timestamp = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000008"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000010"),
                            DurationSeconds = 1800,
                            EventType = "chat_activity",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Timestamp = new DateTime(2025, 1, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000009"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000009"),
                            DurationSeconds = 300,
                            EventType = "message_post",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Timestamp = new DateTime(2024, 12, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            UsageEventId = new Guid("70000000-0000-0000-0000-000000000010"),
                            DeviceId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DurationSeconds = 1800,
                            EventType = "session_start",
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SessionId = new Guid("71000000-0000-0000-0000-000000000010"),
                            Timestamp = new DateTime(2024, 12, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("30000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("AssignmentsInventoryMicroService.Models.UserAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntitlementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ExemptFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignmentId");

                    b.ToTable("user_assignments", (string)null);

                    b.HasData(
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000001"),
                            AssignedAt = new DateTime(2024, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 12, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000002"),
                            AssignedAt = new DateTime(2024, 9, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000002"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 12, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000003"),
                            AssignedAt = new DateTime(2024, 10, 13, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000008"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 12, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000004"),
                            AssignedAt = new DateTime(2024, 10, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 12, 17, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000005"),
                            AssignedAt = new DateTime(2024, 6, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000005"),
                            ExemptFlag = true,
                            LastUsedAt = new DateTime(2024, 12, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000006"),
                            AssignedAt = new DateTime(2024, 11, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000004"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 12, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000007"),
                            AssignedAt = new DateTime(2024, 11, 22, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000006"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 12, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000008"),
                            AssignedAt = new DateTime(2024, 12, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000010"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 12, 29, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000009"),
                            AssignedAt = new DateTime(2024, 10, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000007"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 12, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Status = "Active",
                            UserId = new Guid("30000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            AssignmentId = new Guid("60000000-0000-0000-0000-000000000010"),
                            AssignedAt = new DateTime(2024, 7, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntitlementId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExemptFlag = false,
                            LastUsedAt = new DateTime(2024, 10, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            RevokedAt = new DateTime(2024, 12, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Revoked",
                            UserId = new Guid("30000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("AssignmentsInventoryMicroService.Models.Installation", b =>
                {
                    b.HasOne("AssignmentsInventoryMicroService.Models.Device", "Device")
                        .WithMany("Installations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AssignmentsInventoryMicroService.Models.UsageEvent", b =>
                {
                    b.HasOne("AssignmentsInventoryMicroService.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AssignmentsInventoryMicroService.Models.Device", b =>
                {
                    b.Navigation("Installations");
                });
#pragma warning restore 612, 618
        }
    }
}
