// <auto-generated />
using System;
using IdentityAccessNotificationDbService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityAccessNotificationDbService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126095104_ThirdTes")]
    partial class ThirdTes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Updated workflow #1",
                            ActorId = 1,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "1",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Updated workflow #2",
                            ActorId = 2,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "2",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Updated workflow #3",
                            ActorId = 3,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "3",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Updated workflow #4",
                            ActorId = 4,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "4",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 5,
                            Action = "Updated workflow #5",
                            ActorId = 5,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "5",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 6,
                            Action = "Updated workflow #6",
                            ActorId = 6,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "6",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 7,
                            Action = "Updated workflow #7",
                            ActorId = 7,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "7",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 8,
                            Action = "Updated workflow #8",
                            ActorId = 8,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "8",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 9,
                            Action = "Updated workflow #9",
                            ActorId = 9,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "9",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 10,
                            Action = "Updated workflow #10",
                            ActorId = 10,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "10",
                            EntityType = "Workflow",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"status\":\"Approved\"}",
                            OldValues = "{\"status\":\"Pending\"}",
                            UserAgent = "Mozilla/5.0"
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.Notifications", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Channel = 0,
                            type = "WorkflowUpdate",
                            user_id = 1
                        },
                        new
                        {
                            id = 2,
                            Channel = 1,
                            type = "WorkflowUpdate",
                            user_id = 2
                        },
                        new
                        {
                            id = 3,
                            Channel = 2,
                            type = "WorkflowUpdate",
                            user_id = 3
                        },
                        new
                        {
                            id = 4,
                            Channel = 3,
                            type = "WorkflowUpdate",
                            user_id = 4
                        },
                        new
                        {
                            id = 5,
                            Channel = 0,
                            type = "WorkflowUpdate",
                            user_id = 5
                        },
                        new
                        {
                            id = 6,
                            Channel = 1,
                            type = "WorkflowUpdate",
                            user_id = 6
                        },
                        new
                        {
                            id = 7,
                            Channel = 2,
                            type = "WorkflowUpdate",
                            user_id = 7
                        },
                        new
                        {
                            id = 8,
                            Channel = 3,
                            type = "WorkflowUpdate",
                            user_id = 8
                        },
                        new
                        {
                            id = 9,
                            Channel = 0,
                            type = "WorkflowUpdate",
                            user_id = 9
                        },
                        new
                        {
                            id = 10,
                            Channel = 1,
                            type = "WorkflowUpdate",
                            user_id = 10
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "VIEW_SOFTWARE",
                            Description = "View software catalog"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MANAGE_LICENSES",
                            Description = "Assign or revoke licenses"
                        },
                        new
                        {
                            Id = 3,
                            Code = "VIEW_FINANCE",
                            Description = "View finance reports & allocation"
                        },
                        new
                        {
                            Id = 4,
                            Code = "VIEW_AUDIT",
                            Description = "View audit logs"
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Read-only access",
                            Name = "Viewer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Manage licenses and workflows",
                            Name = "IT Admin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Finance and cost allocation access",
                            Name = "Finance Team"
                        },
                        new
                        {
                            Id = 4,
                            Description = "View audit logs & compliance reports",
                            Name = "Auditor"
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 4
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "IT",
                            Email = "john.admin@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "IT",
                            Email = "sanjay.it@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "Finance",
                            Email = "priya.finance@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "Finance",
                            Email = "rohan.finance@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "Audit",
                            Email = "meera.audit@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "Audit",
                            Email = "dev.audit@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "HR",
                            Email = "arun.viewer@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "Marketing",
                            Email = "tina.viewer@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "Engineering",
                            Email = "raj.employee@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "Engineering",
                            Email = "nisha.employee@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            role_id = 2,
                            user_id = 1
                        },
                        new
                        {
                            Id = 2,
                            role_id = 2,
                            user_id = 2
                        },
                        new
                        {
                            Id = 3,
                            role_id = 3,
                            user_id = 3
                        },
                        new
                        {
                            Id = 4,
                            role_id = 3,
                            user_id = 4
                        },
                        new
                        {
                            Id = 5,
                            role_id = 4,
                            user_id = 5
                        },
                        new
                        {
                            Id = 6,
                            role_id = 4,
                            user_id = 6
                        },
                        new
                        {
                            Id = 7,
                            role_id = 1,
                            user_id = 7
                        },
                        new
                        {
                            Id = 8,
                            role_id = 1,
                            user_id = 8
                        },
                        new
                        {
                            Id = 9,
                            role_id = 1,
                            user_id = 9
                        },
                        new
                        {
                            Id = 10,
                            role_id = 1,
                            user_id = 10
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.WorkFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("RequestedBy");

                    b.ToTable("WorkFlows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovedBy = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "101",
                            EntityType = "License",
                            Payload = "{\"license\":\"Figma\"}",
                            RequestedBy = 9,
                            Status = 0,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ApprovedBy = 2,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = "102",
                            EntityType = "License",
                            Payload = "{\"license\":\"Slack\"}",
                            RequestedBy = 10,
                            Status = 1,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 1, 2, 3, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.AuditLog", b =>
                {
                    b.HasOne("IdentityAccessNotificationDbService.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.WorkFlow", b =>
                {
                    b.HasOne("IdentityAccessNotificationDbService.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityAccessNotificationDbService.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("RequestedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
