// <auto-generated />
using System;
using IdentityAccessNotificationDbService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityAccessNotificationDbService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126092825_FirstTest")]
    partial class FirstTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Performed Action 1",
                            ActorId = 1,
                            CreatedAt = new DateTime(2025, 11, 25, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2144),
                            EntityId = "1",
                            EntityType = "User",
                            IpAddress = "192.168.1.1",
                            NewValues = "{\"new\":1}",
                            OldValues = "{\"old\":1}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Performed Action 2",
                            ActorId = 2,
                            CreatedAt = new DateTime(2025, 11, 24, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2938),
                            EntityId = "2",
                            EntityType = "User",
                            IpAddress = "192.168.1.2",
                            NewValues = "{\"new\":2}",
                            OldValues = "{\"old\":2}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Performed Action 3",
                            ActorId = 3,
                            CreatedAt = new DateTime(2025, 11, 23, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2951),
                            EntityId = "3",
                            EntityType = "User",
                            IpAddress = "192.168.1.3",
                            NewValues = "{\"new\":3}",
                            OldValues = "{\"old\":3}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Performed Action 4",
                            ActorId = 4,
                            CreatedAt = new DateTime(2025, 11, 22, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2958),
                            EntityId = "4",
                            EntityType = "User",
                            IpAddress = "192.168.1.4",
                            NewValues = "{\"new\":4}",
                            OldValues = "{\"old\":4}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 5,
                            Action = "Performed Action 5",
                            ActorId = 5,
                            CreatedAt = new DateTime(2025, 11, 21, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2963),
                            EntityId = "5",
                            EntityType = "User",
                            IpAddress = "192.168.1.5",
                            NewValues = "{\"new\":5}",
                            OldValues = "{\"old\":5}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 6,
                            Action = "Performed Action 6",
                            ActorId = 6,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2969),
                            EntityId = "6",
                            EntityType = "User",
                            IpAddress = "192.168.1.6",
                            NewValues = "{\"new\":6}",
                            OldValues = "{\"old\":6}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 7,
                            Action = "Performed Action 7",
                            ActorId = 7,
                            CreatedAt = new DateTime(2025, 11, 19, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2975),
                            EntityId = "7",
                            EntityType = "User",
                            IpAddress = "192.168.1.7",
                            NewValues = "{\"new\":7}",
                            OldValues = "{\"old\":7}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 8,
                            Action = "Performed Action 8",
                            ActorId = 8,
                            CreatedAt = new DateTime(2025, 11, 18, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2980),
                            EntityId = "8",
                            EntityType = "User",
                            IpAddress = "192.168.1.8",
                            NewValues = "{\"new\":8}",
                            OldValues = "{\"old\":8}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 9,
                            Action = "Performed Action 9",
                            ActorId = 9,
                            CreatedAt = new DateTime(2025, 11, 17, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2984),
                            EntityId = "9",
                            EntityType = "User",
                            IpAddress = "192.168.1.9",
                            NewValues = "{\"new\":9}",
                            OldValues = "{\"old\":9}",
                            UserAgent = "Mozilla/5.0"
                        },
                        new
                        {
                            Id = 10,
                            Action = "Performed Action 10",
                            ActorId = 10,
                            CreatedAt = new DateTime(2025, 11, 16, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(2995),
                            EntityId = "10",
                            EntityType = "User",
                            IpAddress = "192.168.1.10",
                            NewValues = "{\"new\":10}",
                            OldValues = "{\"old\":10}",
                            UserAgent = "Mozilla/5.0"
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.Notifications", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Channel = 1,
                            type = "Notification_Type_1",
                            user_id = 1
                        },
                        new
                        {
                            id = 2,
                            Channel = 2,
                            type = "Notification_Type_2",
                            user_id = 2
                        },
                        new
                        {
                            id = 3,
                            Channel = 3,
                            type = "Notification_Type_3",
                            user_id = 3
                        },
                        new
                        {
                            id = 4,
                            Channel = 0,
                            type = "Notification_Type_4",
                            user_id = 4
                        },
                        new
                        {
                            id = 5,
                            Channel = 1,
                            type = "Notification_Type_5",
                            user_id = 5
                        },
                        new
                        {
                            id = 6,
                            Channel = 2,
                            type = "Notification_Type_6",
                            user_id = 6
                        },
                        new
                        {
                            id = 7,
                            Channel = 3,
                            type = "Notification_Type_7",
                            user_id = 7
                        },
                        new
                        {
                            id = 8,
                            Channel = 0,
                            type = "Notification_Type_8",
                            user_id = 8
                        },
                        new
                        {
                            id = 9,
                            Channel = 1,
                            type = "Notification_Type_9",
                            user_id = 9
                        },
                        new
                        {
                            id = 10,
                            Channel = 2,
                            type = "Notification_Type_10",
                            user_id = 10
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PERM_1",
                            Description = "Permission #1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PERM_2",
                            Description = "Permission #2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PERM_3",
                            Description = "Permission #3"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PERM_4",
                            Description = "Permission #4"
                        },
                        new
                        {
                            Id = 5,
                            Code = "PERM_5",
                            Description = "Permission #5"
                        },
                        new
                        {
                            Id = 6,
                            Code = "PERM_6",
                            Description = "Permission #6"
                        },
                        new
                        {
                            Id = 7,
                            Code = "PERM_7",
                            Description = "Permission #7"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PERM_8",
                            Description = "Permission #8"
                        },
                        new
                        {
                            Id = 9,
                            Code = "PERM_9",
                            Description = "Permission #9"
                        },
                        new
                        {
                            Id = 10,
                            Code = "PERM_10",
                            Description = "Permission #10"
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Role description 1",
                            Name = "Role_1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Role description 2",
                            Name = "Role_2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Role description 3",
                            Name = "Role_3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Role description 4",
                            Name = "Role_4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Role description 5",
                            Name = "Role_5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Role description 6",
                            Name = "Role_6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Role description 7",
                            Name = "Role_7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Role description 8",
                            Name = "Role_8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Role description 9",
                            Name = "Role_9"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Role description 10",
                            Name = "Role_10"
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 10
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D1",
                            Email = "user1@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D2",
                            Email = "user2@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D3",
                            Email = "user3@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D4",
                            Email = "user4@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D5",
                            Email = "user5@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D6",
                            Email = "user6@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D7",
                            Email = "user7@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D8",
                            Email = "user8@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D9",
                            Email = "user9@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = "D10",
                            Email = "user10@company.com",
                            ManagerId = 0,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            role_id = 1,
                            user_id = 1
                        },
                        new
                        {
                            Id = 2,
                            role_id = 2,
                            user_id = 2
                        },
                        new
                        {
                            Id = 3,
                            role_id = 3,
                            user_id = 3
                        },
                        new
                        {
                            Id = 4,
                            role_id = 4,
                            user_id = 4
                        },
                        new
                        {
                            Id = 5,
                            role_id = 5,
                            user_id = 5
                        },
                        new
                        {
                            Id = 6,
                            role_id = 6,
                            user_id = 6
                        },
                        new
                        {
                            Id = 7,
                            role_id = 7,
                            user_id = 7
                        },
                        new
                        {
                            Id = 8,
                            role_id = 8,
                            user_id = 8
                        },
                        new
                        {
                            Id = 9,
                            role_id = 9,
                            user_id = 9
                        },
                        new
                        {
                            Id = 10,
                            role_id = 10,
                            user_id = 10
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.WorkFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("RequestedBy");

                    b.ToTable("WorkFlows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 25, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(7878),
                            EntityId = "1",
                            EntityType = "License",
                            Payload = "{\"workflow\":1}",
                            RequestedBy = 1,
                            Status = 1,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8107)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 24, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8339),
                            EntityId = "2",
                            EntityType = "License",
                            Payload = "{\"workflow\":2}",
                            RequestedBy = 2,
                            Status = 2,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 11, 25, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8340)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 23, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8344),
                            EntityId = "3",
                            EntityType = "License",
                            Payload = "{\"workflow\":3}",
                            RequestedBy = 3,
                            Status = 3,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 11, 24, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8344)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 22, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8347),
                            EntityId = "4",
                            EntityType = "License",
                            Payload = "{\"workflow\":4}",
                            RequestedBy = 4,
                            Status = 4,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8347)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 21, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8350),
                            EntityId = "5",
                            EntityType = "License",
                            Payload = "{\"workflow\":5}",
                            RequestedBy = 5,
                            Status = 0,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 11, 22, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8350)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8352),
                            EntityId = "6",
                            EntityType = "License",
                            Payload = "{\"workflow\":6}",
                            RequestedBy = 6,
                            Status = 1,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 11, 21, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8352)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 19, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8354),
                            EntityId = "7",
                            EntityType = "License",
                            Payload = "{\"workflow\":7}",
                            RequestedBy = 7,
                            Status = 2,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8354)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 18, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8356),
                            EntityId = "8",
                            EntityType = "License",
                            Payload = "{\"workflow\":8}",
                            RequestedBy = 8,
                            Status = 3,
                            Type = 2,
                            UpdatedAt = new DateTime(2025, 11, 19, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8356)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 11, 17, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8358),
                            EntityId = "9",
                            EntityType = "License",
                            Payload = "{\"workflow\":9}",
                            RequestedBy = 9,
                            Status = 4,
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 11, 18, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8358)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 16, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8361),
                            EntityId = "10",
                            EntityType = "License",
                            Payload = "{\"workflow\":10}",
                            RequestedBy = 10,
                            Status = 0,
                            Type = 1,
                            UpdatedAt = new DateTime(2025, 11, 17, 9, 28, 24, 323, DateTimeKind.Utc).AddTicks(8361)
                        });
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.AuditLog", b =>
                {
                    b.HasOne("IdentityAccessNotificationDbService.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("IdentityAccessNotificationDbService.Models.WorkFlow", b =>
                {
                    b.HasOne("IdentityAccessNotificationDbService.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityAccessNotificationDbService.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("RequestedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
