// <auto-generated />
using System;
using CatalogLicensingDbService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogLicensingDbService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126091348_SLMS-Catalog-Initial")]
    partial class SLMSCatalogInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogLicensingDbService.Models.Entitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LicenseTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatsPurchased")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorInvoicePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseTypeId");

                    b.ToTable("Entitlements");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.EntitlementFinance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapexOpex")
                        .HasColumnType("int");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPerSeat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepreciationSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntitlementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntitlementId")
                        .IsUnique();

                    b.ToTable("EntitlementFinances");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.LicenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumptionMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnforcementType")
                        .HasColumnType("int");

                    b.Property<int>("LicenseTypeName")
                        .HasColumnType("int");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareCatalogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareCatalogId");

                    b.ToTable("LicenseTypes");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.Procurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Procurements");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.ProcurementEntitlementMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntitlementId")
                        .HasColumnType("int");

                    b.Property<int>("ProcurementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntitlementId");

                    b.HasIndex("ProcurementId");

                    b.ToTable("ProcurementEntitlementMaps");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.SoftwareCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareCatalogs");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.Entitlement", b =>
                {
                    b.HasOne("CatalogLicensingDbService.Models.LicenseType", "LicenseType")
                        .WithMany("Entitlements")
                        .HasForeignKey("LicenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicenseType");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.EntitlementFinance", b =>
                {
                    b.HasOne("CatalogLicensingDbService.Models.Entitlement", "Entitlement")
                        .WithOne("Finance")
                        .HasForeignKey("CatalogLicensingDbService.Models.EntitlementFinance", "EntitlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entitlement");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.LicenseType", b =>
                {
                    b.HasOne("CatalogLicensingDbService.Models.SoftwareCatalog", "SoftwareCatalog")
                        .WithMany("LicenseTypes")
                        .HasForeignKey("SoftwareCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareCatalog");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.ProcurementEntitlementMap", b =>
                {
                    b.HasOne("CatalogLicensingDbService.Models.Entitlement", "Entitlement")
                        .WithMany("ProcurementMaps")
                        .HasForeignKey("EntitlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogLicensingDbService.Models.Procurement", "Procurement")
                        .WithMany("ProcurementEntitlements")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entitlement");

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.Entitlement", b =>
                {
                    b.Navigation("Finance")
                        .IsRequired();

                    b.Navigation("ProcurementMaps");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.LicenseType", b =>
                {
                    b.Navigation("Entitlements");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.Procurement", b =>
                {
                    b.Navigation("ProcurementEntitlements");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.SoftwareCatalog", b =>
                {
                    b.Navigation("LicenseTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
