// <auto-generated />
using System;
using CatalogLicensingDbService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogLicensingDbService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogLicensingDbService.Models.Entitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LicenseTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatsPurchased")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorInvoicePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseTypeId");

                    b.ToTable("Entitlements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationMethod = "SSO",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 1,
                            PurchaseDate = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 50,
                            Sku = "PS-100",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/ps1.pdf"
                        },
                        new
                        {
                            Id = 2,
                            ActivationMethod = "Server",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 2,
                            PurchaseDate = new DateTime(2022, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 4,
                            Sku = "ORA-CPU-01",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/oracle.pdf"
                        },
                        new
                        {
                            Id = 3,
                            ActivationMethod = "Account",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 3,
                            PurchaseDate = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 100,
                            Sku = "JIRA-CLD",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/jira1.pdf"
                        },
                        new
                        {
                            Id = 4,
                            ActivationMethod = "SSO",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 4,
                            PurchaseDate = new DateTime(2025, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 300,
                            Sku = "MS-365",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/ms1.pdf"
                        },
                        new
                        {
                            Id = 5,
                            ActivationMethod = "Account",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 5,
                            PurchaseDate = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 20,
                            Sku = "FGM-CLOUD",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/figma.pdf"
                        },
                        new
                        {
                            Id = 6,
                            ActivationMethod = "Key",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 6,
                            PurchaseDate = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 10,
                            Sku = "VS-PRO",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/vs1.pdf"
                        },
                        new
                        {
                            Id = 7,
                            ActivationMethod = "Account",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 7,
                            PurchaseDate = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 50,
                            Sku = "POSTMAN-1",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/pm.pdf"
                        },
                        new
                        {
                            Id = 8,
                            ActivationMethod = "SSO",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiryDate = new DateTime(2027, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 8,
                            PurchaseDate = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 200,
                            Sku = "SLK-TEAM",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/slack.pdf"
                        },
                        new
                        {
                            Id = 9,
                            ActivationMethod = "HW Lock",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 9,
                            PurchaseDate = new DateTime(2023, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 10,
                            Sku = "ACAD-01",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/acad.pdf"
                        },
                        new
                        {
                            Id = 10,
                            ActivationMethod = "Server",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseTypeId = 10,
                            PurchaseDate = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeatsPurchased = 3,
                            Sku = "VMW-ESXI",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorInvoicePath = "/inv/esxi.pdf"
                        });
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.EntitlementFinance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapexOpex")
                        .HasColumnType("int");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPerSeat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepreciationSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntitlementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntitlementId")
                        .IsUnique();

                    b.ToTable("EntitlementFinances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapexOpex = 0,
                            CostCenter = "Design",
                            CostPerSeat = 12000m,
                            CostTotal = 600000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            DepreciationSchedule = "{}",
                            EntitlementId = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CapexOpex = 0,
                            CostCenter = "IT",
                            CostPerSeat = 50000m,
                            CostTotal = 200000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DepreciationSchedule = "{}",
                            EntitlementId = 2,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CapexOpex = 1,
                            CostCenter = "PMO",
                            CostPerSeat = 1500m,
                            CostTotal = 150000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DepreciationSchedule = "{}",
                            EntitlementId = 3,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CapexOpex = 1,
                            CostCenter = "IT",
                            CostPerSeat = 2600m,
                            CostTotal = 800000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            DepreciationSchedule = "{}",
                            EntitlementId = 4,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CapexOpex = 1,
                            CostCenter = "Design",
                            CostPerSeat = 12500m,
                            CostTotal = 250000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            DepreciationSchedule = "{}",
                            EntitlementId = 5,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CapexOpex = 0,
                            CostCenter = "Dev",
                            CostPerSeat = 50000m,
                            CostTotal = 500000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            DepreciationSchedule = "{}",
                            EntitlementId = 6,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CapexOpex = 1,
                            CostCenter = "QA",
                            CostPerSeat = 2000m,
                            CostTotal = 100000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DepreciationSchedule = "{}",
                            EntitlementId = 7,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CapexOpex = 1,
                            CostCenter = "IT",
                            CostPerSeat = 1500m,
                            CostTotal = 300000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DepreciationSchedule = "{}",
                            EntitlementId = 8,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CapexOpex = 0,
                            CostCenter = "Engineering",
                            CostPerSeat = 70000m,
                            CostTotal = 700000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "INR",
                            DepreciationSchedule = "{}",
                            EntitlementId = 9,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CapexOpex = 0,
                            CostCenter = "Infra",
                            CostPerSeat = 300000m,
                            CostTotal = 900000m,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DepreciationSchedule = "{}",
                            EntitlementId = 10,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.LicenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumptionMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnforcementType")
                        .HasColumnType("int");

                    b.Property<int>("LicenseTypeName")
                        .HasColumnType("int");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareCatalogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareCatalogId");

                    b.ToTable("LicenseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumptionMethod = 0,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 2,
                            LicenseTypeName = 1,
                            Metric = 0,
                            SoftwareCatalogId = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "Adobe ETLA"
                        },
                        new
                        {
                            Id = 2,
                            ConsumptionMethod = 1,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 4,
                            LicenseTypeName = 0,
                            Metric = 2,
                            SoftwareCatalogId = 2,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "Oracle CPU Rules"
                        },
                        new
                        {
                            Id = 3,
                            ConsumptionMethod = 0,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 1,
                            LicenseTypeName = 3,
                            Metric = 0,
                            SoftwareCatalogId = 3,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "Atlassian Cloud"
                        },
                        new
                        {
                            Id = 4,
                            ConsumptionMethod = 0,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 2,
                            LicenseTypeName = 1,
                            Metric = 0,
                            SoftwareCatalogId = 4,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "Microsoft Enterprise"
                        },
                        new
                        {
                            Id = 5,
                            ConsumptionMethod = 2,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 1,
                            LicenseTypeName = 3,
                            Metric = 0,
                            SoftwareCatalogId = 5,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "Figma Cloud"
                        },
                        new
                        {
                            Id = 6,
                            ConsumptionMethod = 0,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 0,
                            LicenseTypeName = 0,
                            Metric = 1,
                            SoftwareCatalogId = 6,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "MS VS License"
                        },
                        new
                        {
                            Id = 7,
                            ConsumptionMethod = 0,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 1,
                            LicenseTypeName = 3,
                            Metric = 0,
                            SoftwareCatalogId = 7,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "Postman Cloud"
                        },
                        new
                        {
                            Id = 8,
                            ConsumptionMethod = 2,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 2,
                            LicenseTypeName = 3,
                            Metric = 0,
                            SoftwareCatalogId = 8,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "Slack Cloud"
                        },
                        new
                        {
                            Id = 9,
                            ConsumptionMethod = 0,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 3,
                            LicenseTypeName = 0,
                            Metric = 1,
                            SoftwareCatalogId = 9,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "Autodesk License"
                        },
                        new
                        {
                            Id = 10,
                            ConsumptionMethod = 1,
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforcementType = 4,
                            LicenseTypeName = 0,
                            Metric = 3,
                            SoftwareCatalogId = 10,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            VendorTerms = "VMware Terms"
                        });
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.Procurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Procurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = "CON-PS-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-1001",
                            PurchaseOrderNumber = "PO-1001",
                            ResellerName = "Softline India",
                            SupportLevel = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ContractId = "CON-ORA-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-2001",
                            PurchaseOrderNumber = "PO-2001",
                            ResellerName = "Redington",
                            SupportLevel = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ContractId = "CON-JIRA-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-3001",
                            PurchaseOrderNumber = "PO-3001",
                            ResellerName = "ACPL",
                            SupportLevel = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ContractId = "CON-MS-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-4001",
                            PurchaseOrderNumber = "PO-4001",
                            ResellerName = "Softcell",
                            SupportLevel = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ContractId = "CON-FGM-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-5001",
                            PurchaseOrderNumber = "PO-5001",
                            ResellerName = "Ingram",
                            SupportLevel = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ContractId = "CON-VS-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-6001",
                            PurchaseOrderNumber = "PO-6001",
                            ResellerName = "Wipro",
                            SupportLevel = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            ContractId = "CON-PM-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-7001",
                            PurchaseOrderNumber = "PO-7001",
                            ResellerName = "Redington",
                            SupportLevel = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            ContractId = "CON-SLK-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-8001",
                            PurchaseOrderNumber = "PO-8001",
                            ResellerName = "ACPL",
                            SupportLevel = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            ContractId = "CON-ACAD-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-9001",
                            PurchaseOrderNumber = "PO-9001",
                            ResellerName = "Softcell",
                            SupportLevel = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            ContractId = "CON-VMW-01",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceId = "INV-10001",
                            PurchaseOrderNumber = "PO-10001",
                            ResellerName = "Ingram",
                            SupportLevel = 1,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.ProcurementEntitlementMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntitlementId")
                        .HasColumnType("int");

                    b.Property<int>("ProcurementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntitlementId");

                    b.HasIndex("ProcurementId");

                    b.ToTable("ProcurementEntitlementMaps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntitlementId = 1,
                            ProcurementId = 1
                        },
                        new
                        {
                            Id = 2,
                            EntitlementId = 2,
                            ProcurementId = 2
                        },
                        new
                        {
                            Id = 3,
                            EntitlementId = 3,
                            ProcurementId = 3
                        },
                        new
                        {
                            Id = 4,
                            EntitlementId = 4,
                            ProcurementId = 4
                        },
                        new
                        {
                            Id = 5,
                            EntitlementId = 5,
                            ProcurementId = 5
                        },
                        new
                        {
                            Id = 6,
                            EntitlementId = 6,
                            ProcurementId = 6
                        },
                        new
                        {
                            Id = 7,
                            EntitlementId = 7,
                            ProcurementId = 7
                        },
                        new
                        {
                            Id = 8,
                            EntitlementId = 8,
                            ProcurementId = 8
                        },
                        new
                        {
                            Id = 9,
                            EntitlementId = 9,
                            ProcurementId = 9
                        },
                        new
                        {
                            Id = 10,
                            EntitlementId = 10,
                            ProcurementId = 10
                        });
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.SoftwareCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareCatalogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Design",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Image editing suite",
                            ProductName = "Adobe Photoshop",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Adobe"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Enterprise RDBMS",
                            ProductName = "Oracle DB",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Oracle"
                        },
                        new
                        {
                            Id = 3,
                            Category = "PM",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Project Management",
                            ProductName = "Jira",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Atlassian"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Productivity",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Office Suite",
                            ProductName = "MS Office",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Microsoft"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Design",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "UI/UX Design",
                            ProductName = "Figma",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Figma Inc"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Development",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Development IDE",
                            ProductName = "Visual Studio",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Microsoft"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Development",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "API Testing Tool",
                            ProductName = "Postman",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Postman Inc"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Communication",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Communication",
                            ProductName = "Slack",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Slack Tech"
                        },
                        new
                        {
                            Id = 9,
                            Category = "CAD",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Engineering Design",
                            ProductName = "AutoCAD",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "Autodesk"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Infrastructure",
                            CreatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Virtualization platform",
                            ProductName = "VMware ESXi",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Vendor = "VMware"
                        });
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.Entitlement", b =>
                {
                    b.HasOne("CatalogLicensingDbService.Models.LicenseType", "LicenseType")
                        .WithMany("Entitlements")
                        .HasForeignKey("LicenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicenseType");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.EntitlementFinance", b =>
                {
                    b.HasOne("CatalogLicensingDbService.Models.Entitlement", "Entitlement")
                        .WithOne("Finance")
                        .HasForeignKey("CatalogLicensingDbService.Models.EntitlementFinance", "EntitlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entitlement");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.LicenseType", b =>
                {
                    b.HasOne("CatalogLicensingDbService.Models.SoftwareCatalog", "SoftwareCatalog")
                        .WithMany("LicenseTypes")
                        .HasForeignKey("SoftwareCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareCatalog");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.ProcurementEntitlementMap", b =>
                {
                    b.HasOne("CatalogLicensingDbService.Models.Entitlement", "Entitlement")
                        .WithMany("ProcurementMaps")
                        .HasForeignKey("EntitlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogLicensingDbService.Models.Procurement", "Procurement")
                        .WithMany("ProcurementEntitlements")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entitlement");

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.Entitlement", b =>
                {
                    b.Navigation("Finance")
                        .IsRequired();

                    b.Navigation("ProcurementMaps");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.LicenseType", b =>
                {
                    b.Navigation("Entitlements");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.Procurement", b =>
                {
                    b.Navigation("ProcurementEntitlements");
                });

            modelBuilder.Entity("CatalogLicensingDbService.Models.SoftwareCatalog", b =>
                {
                    b.Navigation("LicenseTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
